version: '3'
services:
  derper:
    image: fredliang/derper
    restart: always
    ports:
      - "3478:3478/udp"
      - "5050:5050"
    volumes:
      - ./cert:/cert
    environment:
      DERP_DOMAIN: derp.domain 
      DERP_ADDR: ":5050"
      DERP_CERT_MODE: manual
      DERP_CERT_DIR: /cert

